paises_africanos = {
    'Argélia': 'Argel',
    'Angola': 'Luanda',
    'Benin': 'Porto Novo',
    'Botsuana': 'Gaborone',
    'Burquina Faso': 'Ouagadougou',
    'Burundi': 'Bujumbura',
    'Cabo Verde': 'Praia',
    'Camarões': 'Yaoundé',
    'Chade': 'Djamena',
    'Comores': 'Moroni',
    'Congo': 'Brazzaville',
    'Costa do Marfim': 'Yamoussoukro',
    'Djibuti': 'Djibuti',
    'Egito': 'Cairo',
    'Eritreia': 'Asmara',
    'Eswatini': 'Lobamba',
    'Etiópia': 'Adis Abeba',
    'Gabão': 'Libreville',
    'Gâmbia': 'Banjul',
    'Gana': 'Acra',
    'Guiné': 'Conacri',
    'Guiné-Bissau': 'Bissau',
    'Guiné Equatorial': 'Malabo',
    'Lesoto': 'Maseru',
    'Libéria': 'Monróvia',
    'Líbia': 'Trípoli',
    'Madagáscar': 'Antananarivo',
    'Maláui': 'Lilongwe',
    'Mali': 'Bamako',
    'Marrocos': 'Rabat',
    'Maurícia': 'Port Louis',
    'Mauritânia': 'Nouakchott',
    'Moçambique': 'Maputo',
    'Namíbia': 'Windhoek',
    'Níger': 'Niamey',
    'Nigéria': 'Abuja',
    'Quênia': 'Nairóbi',
    'Ruanda': 'Quigali',
    'São Tomé e Príncipe': 'São Tomé',
    'Senegal': 'Dacar',
    'Seicheles': 'Victoria',
    'Serra Leoa': 'Freetown',
    'Somália': 'Mogadíscio',
    'Sudão': 'Cartum',
    'Sudão do Sul': 'Juba',
    'Tanzânia': 'Dodoma',
    'Togo': 'Lomé',
    'Tunísia': 'Túnis',
    'Uganda': 'Kampala',
    'Zâmbia': 'Lusaka',
    'Zimbábue': 'Harare'
}

frutas_tropicais = [
    'Abacaxi',
    'Manga',
    'Goiaba',
    'Banana',
    'Coco',
    'Maracujá',
    'Caju',
    'Abacate',
    'Pitaya',
    'Graviola',
    'Kiwi',
    'Papaya',
    'Jabuticaba',
    'Lichia',
    'Rambutã'
]

frutas_nutricao = {
    'Abacaxi': {'Calorias': 50, 'Vitamina C': 47, 'Fibras': 2.3},
    'Manga': {'Calorias': 60, 'Vitamina A': 54, 'Vitamina C': 60},
    'Goiaba': {'Calorias': 68, 'Vitamina C': 228, 'Fibras': 8.9},
    'Banana': {'Calorias': 105, 'Potássio': 422, 'Vitamina B6': 0.4},
    'Coco': {'Calorias': 354, 'Água': 100, 'Gorduras': 33.5},
    'Maracujá': {'Calorias': 17, 'Vitamina C': 20, 'Fibras': 5.4},
    'Caju': {'Calorias': 43, 'Vitamina C': 218, 'Fibras': 0.9},
    'Abacate': {'Calorias': 160, 'Gorduras': 14.7, 'Fibras': 6.7},
    'Pitaya': {'Calorias': 60, 'Fibras': 9, 'Vitamina C': 9},
    'Graviola': {'Calorias': 66, 'Fibras': 3.3, 'Vitamina C': 20},
    'Kiwi': {'Calorias': 61, 'Vitamina C': 92, 'Fibras': 3},
    'Papaya': {'Calorias': 59, 'Vitamina C': 62, 'Fibras': 2.5},
    'Jabuticaba': {'Calorias': 58, 'Fibras': 4.9, 'Vitamina C': 13},
    'Lichia': {'Calorias': 66, 'Vitamina C': 136, 'Fibras': 2.3},
    'Rambutã': {'Calorias': 68, 'Vitamina C': 20, 'Fibras': 0.9}
}

frutas = ["Maça","Limão","Pera",]